# Generated by Django 4.2 on 2024-09-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AddField(
            model_name='file',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is_enable'),
        ),
    ]
